# =========================================================== #
#                     ESPANSO CONFIG                          #
# =========================================================== #

# Variaveis globais
global_vars: #define o tempo.
  - name: "tempo"
    type: "shell"
    params:
      cmd: "$HOME/.config/espanso/scripts/tempo.sh"

  - name: "pass"
    type: "shell"
    params:
      cmd: "bash $HOME/.config/espanso/scripts/pass-gen.sh -l 16"

matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/

  ############## ATENDIMENTO #################

  ##### inatividade
  - trigger: ":20min"
    replace: |
      Poxa! 😕
      O atendimento está sendo finalizado devido a falta de comunicação e inatividade. Estamos à sua disposição das 08:00 às 22:00. Seu provedor de internet, AraujoSat, agradece a preferência, {{tempo}}!

  ##### final do expediente
  - trigger: ":10hrs"
    replace: "Devido ao final do expediente 22:00 horas o sistema esta finalizando o chat, se o problema persistir entrar em contato por este mesmo canal a partir das 8 Horas, para que seja reavaliado o problema. {{tempo}}"

  ##### ABERTA 0S
  - trigger: ":os"
    replace: "Foi aberta uma ordem de serviço e o prazo contratual para a realização da visita é de até 48 horas úteis. Estamos empenhados em realizar a visita o quanto antes, mas por enquanto, posso ajudar em mais alguma coisa?"

  ##### DADOS DO CLIENTE
  - trigger: ":dados"
    replace: |
      Será necessário antes, confirmar alguns dados do titular do contrato tudo bem?
      1 - CPF:
      2 - NOME COMPLETO:
      3 - ENDEREÇO:

  ##### ENCERRAR ATENDIMENTO
  - trigger: ":por nada"
    replace: "A equipe da AraujoSat agradece pela sua paciência. {{tempo}}!"

  ##### ALGO MAIS?
  - trigger: ":algo mais"
    replace: |
      Por hora te ajudo mais alguma solicitação?

  #### Local fora.
  - trigger: ":geral"
    replace: |
      A falta de acesso ou instabilidade na conexão, foi devido a um problema na localidade. Já designamos uma equipe para verificar.
      No momento só aguardar.

  ##### Gerador de senhas
  - trigger: ":pass"
    replace: "{{pass}}"

  #### Energia.
  - trigger: ":energia"
    replace: |
      Caro(a) Cliente, queremos informar que houve uma *falta de energia* na área onde você está conectado(a), o que está causando a indisponibilidade dos nossos serviços temporariamente. Estamos trabalhando para resolver essa situação o mais rápido possível. Pedimos desculpas pelo transtorno e agradecemos pela sua compreensão.

      Ainda não temos um prazo exato, mas esperamos que tudo volte ao normal em breve.
      A equipe da AraujoSat agradece pela sua paciência. {{tempo}}!

  #### Acesso lento.
  - trigger: ":triagem"
    replace: |
      Prezado(a) Cliente, poderia realizar os procedimentos de triagem inicial?

      1 - *Reinicie seus equipamentos:*
      - Desligue os equipamentos da tomada por pelo menos 1 minuto e depois ligue novamente.
      - Reinicie os dispositivos que apresentam o problema.
      2 - *Reconecte e verifique:*
      - Reconecte os dispositivos.
      - Verifique se o problema persiste.

      Essas etapas simples podem resolver problemas comuns. Se o problema persistir, por favor explique com mais detalhes como ele está ocorrendo.

  #### Informe melhor o problema por favor.
  - trigger: ":detalhes"
    replace: |
      Após análise, não detectamos problemas nos equipamentos da sua residência.

      Para oferecer uma assistência mais precisa, solicitamos que forneça detalhes adicionais sobre o problema que está enfrentando. Por favor, descreva com mais detalhes como esse problema ocorre, quais atividades são mais afetadas e se há horários específicos em que o problema ocorre.

  #### Informe melhor o problema por favor.
  - trigger: ":ajustes"
    replace: "Foram realizados alguns ajustes nos equipamentos, por gentileza, \
    teste novamente sua conexão neste momento e informe se está tudo ok."

  #### Tv Box
  - trigger: ":tvbox"
    replace: "Recomendamos a não utilização de plataformas do tipo, já que a mesma permite a ciculação \
    de produtos não legalizados em sua plataforma compromentendo assim os dados do usuário e sua integridade. \
    No mais não fornecemos suporte ao serviço e futuros atendimentos relacionado a esse serviço não serão continuados."

  #### Reduzido(a)
  - triggers: [":reduzido",":reduzida"]
    replace: |
      Sua conexão está *reduzida* devido a parcela referente ao dia {{clipboard}}
      Saberia informar se já foi paga?
    vars:
      - name: "clipboard"
        type: "clipboard"

#### Suspenso
  - trigger: ":suspenso"
    replace: |
      Sua conexão está *suspensa* devido ao atraso com mais de 30 da parcela referente ao dia {{clipboard}}
      Saberia informar se já foi paga?"
    vars:
      - name: "clipboard"
        type: "clipboard"

#### Local expecifico fora
  - trigger: ":fora"
    replace: "Desculpe o inconveniente, estamos com problema de falta de energia na localidade, \
    afetado a sua conexão e a de demais clientes, porém estamos trabalhando na solução para restabelecer \
    a conexão o mais rápido possível."

#### Esgotamento de banda
  - trigger: ":velocidade"
    replace: "Prezado(a) cliente, sua conexão está lenta devido ao fato de que a velocidade \
    da sua internet está sendo *completamente consumida*, o que causa lentidão em nossos serviços."

#### Manutenção não programada.
  - trigger: ":man"
    replace: "Prezado(a), sua localidade está passando por uma *manutenção não programada*, \
    sua conexão retornará em breve!! 🙂"