# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# Variaveis globais
global_vars: #define o tempo.
  - name: "tempo"
    type: "shell"
    params:
      cmd: "$HOME/.config/espanso/scripts/tempo.sh"

  - name: "pass"
    type: "shell"
    params:
      cmd: "bash $HOME/.config/espanso/scripts/pass-gen.sh -l 16"

matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/


############## ATENDIMENTO #################

##### inatividade
  - trigger: ":20min"
    replace: |
              Poxa! 😕
              O atendimento está sendo finalizado devido a falta de comunicação e inatividade. Estamos à sua disposição das 08:00 às 22:00. Seu provedor de internet, AraujoSat, agradece a preferência, {{tempo}}!


##### final do expediente
  - trigger: ":10hrs"
    replace: "Devido ao final do expediente 22:00 horas o sistema esta finalizando o chat, se o problema persistir entrar em contato por este mesmo canal a partir das 8 Horas, para que seja reavaliado o problema. {{tempo}}"

##### ABERTA 0S
  - trigger: ":os"
    replace: "Foi aberta uma ordem de serviço e o prazo contratual para a realização da visita é de até 48 horas úteis. Estamos empenhados em realizar a visita o quanto antes, mas por enquanto, posso ajudar em mais alguma coisa?"

##### DADOS DO CLIENTE 
  - trigger: ":dados"
    replace: |
              Será necessário antes, confirmar alguns dados do titular do contrato tudo bem?
              1 - CPF:
              2 - NOME COMPLETO:
              3 - ENDEREÇO:
##### ENCERRAR ATENDIMENTO
  - trigger: ":por nada"
    replace: "A equipe da AraujoSat agradece pela sua paciência. {{tempo}}!"
##### ALGO MAIS?
  - trigger: ":algo mais"
    replace: |
              Por hora te ajudo mais alguma solicitação?
#### Local fora.
  - trigger: ":geral"
    replace: |
              A falta de acesso ou instabilidade na conexão, foi devido a um problema na localidade. Já designamos uma equipe para verificar.
              No momento só aguardar.
##### Gerador de senhas
  - trigger: ":pass"
    replace: "{{pass}}"
#### Energia.
  - trigger: ":energia"
    replace: |
              Prezado(a) Cliente,
              Informamos que, devido a uma falta de energia na sua localidade, a sua conexão à Internet encontra-se temporariamente indisponível. Estamos trabalhando para resolver a situação o mais rápido possível. Lamentamos o inconveniente e agradecemos pela compreensão.
              A equipe da AraujoSat agradece pela sua paciência. {{tempo}}!
